apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - deployment.yaml
  # Disabling worker to save on Kubernetes resources while it is not in active use
  # - worker.yaml
images:
  - name: dannylongeuay/ndsq-pyapi
    newTag: 1.2.0
