name: Code Quality Check
on:
  pull_request:
    paths:
      - "app/**"
      - "tests/**"
      - "poetry.lock"
jobs:
  cq-check:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.1.11
      - name: Install dependencies
        run: poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: Run Code Quality Check
        run: make cq-check