name: Release and Publish
on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "Dockerfile"
      - "poetry.lock"
jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.gsr_action.outputs.version}}
    steps:
      - uses: actions/checkout@master
      - uses: go-semantic-release/action@v1
        id: gsr_action
        with:
          update-file: ./deploy/kustomization/kustomization.yaml
          github-token: ${{ secrets.GITHUB_TOKEN }}
  publish:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: dannylongeuay/ndsq-pyapi
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{needs.release.outputs.version}}"
